### ISSUE TITLE
The "CodeTool\ElasticSearch\DSL\ElasticSearchSearchSource::$from" parameter never set u

### ISSUE THREAD

**Issue by ftw-soft** [code-tool/es-dsl-lb#7]
https://github.com/code-tool/es-dsl-lb/blob/88a5a51085c78f38995c173c2135ddf36a85a9f1/src/CodeTool/ElasticSearch/DSL/ElasticSearchSearchSource.php#L104

You have defined "from" property, but you forgot about setter

**Comment by SirSova** [comment]
Up

**Comment by asp24** [comment]
Fixed
